##### Build bricksync
FROM alpine:latest as builder

RUN apk add gcc libc-dev libressl-dev git

RUN git clone https://github.com/ZZJHONS/Bricksync.git

WORKDIR /bricksync/src/
RUN ./compile


##### Finally prepare our container
FROM alpine:latest

RUN apk add libressl-dev

COPY --from=builder /bricksync/src/bricksync .

ENTRYPOINT ["/bricksync"]
