##### Build bricksync
FROM node:alpine as bricksyncbuilder

RUN apk add gcc libc-dev libressl-dev git

RUN git clone https://github.com/ZZJHONS/Bricksync.git

WORKDIR /Bricksync/
RUN chmod +x ./compile
RUN ./compile


##### Install npm dependencies
FROM node:alpine as uibuilder

COPY bricksync-ui/ /home/node/bricksync-ui/
WORKDIR /home/node/bricksync-ui/
RUN npm install


##### Finally prepare our container
FROM node:alpine

RUN apk add libressl-dev screen

COPY --from=bricksyncbuilder /Bricksync/bricksync .
COPY entrypoint.sh .

ENV PORT=8080
EXPOSE 8080

COPY --from=uibuilder /home/node/bricksync-ui/ /home/node/bricksync-ui/
WORKDIR /home/node/bricksync-ui/

ENTRYPOINT ["/entrypoint.sh"]
