##### Build bricksync
FROM node:alpine as bricksyncbuilder

RUN apk add gcc libc-dev libressl-dev git

RUN git clone https://github.com/ZZJHONS/Bricksync.git

WORKDIR /Bricksync/
RUN chmod +x ./compile
RUN ./compile


##### Finally prepare our container
FROM alpine:latest

RUN apk add libressl-dev

COPY --from=bricksyncbuilder /Bricksync/bricksync .

ENTRYPOINT ["/bricksync"]
