name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DATE_TAG: ${{ date +%Y%m%d%H%M }} # This variable is available to all jobs

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username Area128 --password ${{ secrets.REG_TOKEN }} ghcr.io
        docker build . --file Dockerfile.ui --tag ghcr.io/area128/bricksync-ui:${{ env.DATE_TAG }}
        docker image tag ghcr.io/area128/bricksync-ui:${{ env.DATE_TAG }} ghcr.io/area128/bricksync-ui:latest
        docker push ghcr.io/area128/bricksync-ui:${{ env.DATE_TAG }}
        docker push ghcr.io/area128/bricksync-ui:latest
