name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username Area128 --password ${{ secrets.REG_TOKEN }} ghcr.io
        docker build . --file Dockerfile.ui --tag ghcr.io/area128/bricksync-docker:ui-${{ steps.date.outputs.date }}
        docker image tag ghcr.io/area128/bricksync-docker:ui-${{ steps.date.outputs.date }} ghcr.io/area128/bricksync-docker:latest
        docker push ghcr.io/area128/bricksync-docker:ui-${{ steps.date.outputs.date }}
        docker push ghcr.io/area128/bricksync-docker:latest
